---
- name: install tree package
  hosts: localhost
  tasks:
    - name: install tree
      ansible.builtin.dnf:
        name: tree # install tree package
        state: present # to install any package software
